const applePear = [
  {
    id: 'product01',
    link: '../detail_food_fruit/apple.html',
    img: './images/fruit_01.jpg',
    imgOn: './images/fruit_01_on.jpg',
    logo: '이마트몰',
    delivery: '',
    fresh: '신선보장',
    emartFresh: 'E-MART FRESH',
    name: '유명산지 사과 4~11입/봉 (1.8kg)',
    price: '10,800',
    won: '원',
    sale: '12,800',
    saleWon: '원'
  },
  {
    id: 'product02',
    link: '#!',
    img: './images/fruit_02.jpg',
    imgOn: './images/fruit_02_on.jpg',
    logo: '이마트몰',
    delivery: '',
    fresh: '신선보장',
    emartFresh: '',
    name: '저탄소인증 사과 1.4kg/봉',
    price: '7,980',
    won: '원',
    sale: '',
    saleWon: ''
  },
  {
    id: 'product03',
    link: '#!',
    img: './images/fruit_03.jpg',
    imgOn: './images/fruit_03_on.jpg',
    logo: '이마트몰',
    delivery: '새벽배송',
    fresh: '신선보장',
    emartFresh: '',
    name: '[당도선별] 유명산지 청송 햇 홍로사과 1.5kg (봉)',
    price: '9,800',
    won: '원',
    sale: '12,800',
    saleWon: '원'
  },
  {
    id: 'product04',
    link: '#!',
    img: './images/fruit_04.jpg',
    imgOn: './images/fruit_04_on.jpg',
    logo: '이마트몰',
    delivery: '',
    fresh: '신선보장',
    emartFresh: '',
    name: 'GAP 죽장사과 4~6입/봉 (1.3kg내외)',
    price: '5,980',
    won: '원',
    sale: '',
    saleWon: ''
  },
  {
    id: 'product05',
    link: '#!',
    img: './images/fruit_05.jpg',
    imgOn: './images/fruit_05_on.jpg',
    logo: '이마트몰',
    delivery: '새벽배송',
    fresh: '신선보장',
    emartFresh: '',
    name: '못생겨도 맛좋은 보조개 햇 홍로사과 3kg (봉)',
    price: '12,800',
    won: '원',
    sale: '14,800',
    saleWon: '원'
  },
  {
    id: 'product06',
    link: '#!',
    img: './images/fruit_06.jpg',
    imgOn: './images/fruit_06_on.jpg',
    logo: '이마트몰',
    delivery: '',
    fresh: '신선보장',
    emartFresh: '친환경 자연주의',
    name: '저탄소인증 세척사과 2kg/박스',
    price: '13,800',
    won: '원',
    sale: '',
    saleWon: ''
  },
  {
    id: 'product07',
    link: '#!',
    img: './images/fruit_07.jpg',
    imgOn: './images/fruit_07_on.jpg',
    logo: '이마트몰',
    delivery: '새벽배송',
    fresh: '신선보장',
    emartFresh: '',
    name: '[당도선별] 천안 신고배 3입 1.9kg (팩)',
    price: '12,800',
    won: '원',
    sale: '15,800',
    saleWon: '원'
  },
  {
    id: 'product08',
    link: '#!',
    img: './images/fruit_08.jpg',
    imgOn: './images/fruit_08_on.jpg',
    logo: '이마트몰',
    delivery: '',
    fresh: '신선보장',
    emartFresh: '친환경 자연주의',
    name: '저탄소인증 배3~4입/봉 (1.8kg내외)',
    price: '9,980',
    won: '원',
    sale: '',
    saleWon: ''
  }
]

export default applePear